language: python
cache:
- pip
sudo: false
branches:
  only:
  - src
python:
- 3.6
before_install:
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- openssl aes-256-cbc -K $encrypted_ce13325feee7_key -iv $encrypted_ce13325feee7_iv
  -in id_rsa.enc -out id_rsa -d
- git config --global user.name 'enderTree'
- git config --global user.email 'endepearl@163.com'
- git config --global push.default 'simple'
- echo -e 'Host github.com\n    StrictHostKeyChecking no' >> ~/.ssh/config
- eval "$(ssh-agent -s)"
- chmod 600 id_rsa
- ssh-add id_rsa
- git remote rm origin
- git remote add origin git@github.com:enderTree/enderTree.github.io.git
- git fetch origin master
- git branch master FETCH_HEAD
install:
- pip install 'Nikola[extras]'
script:
- nikola build && nikola github_deploy -m 'Nikola auto deploy [ci skip]'
notifications:
  email:
    on_success: change
    on_failure: always
